sprint4
tommypanda10/MovieQuiz-ios pull request #2
Opened 2022-11-22 18:16 UTC by tommypanda10

2022-11-23 13:46 UTC, mmbabaev requested changes

2022-11-23 13:46 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction private func yesButtonClicked(_ sender: UIButton) {
порядок в viewController обычно делают такой: 

1. Properties
2. override funcs
3. IBAction funcs
4. other funcs

2022-11-23 13:46 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        self.show(quiz: convert(model: currentQuestion))
тут это не влияет ни на что, но в целом рекомендую `super.viewDidLoad` в самом начале вызывать

2022-11-23 13:46 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.borderColor = isCorrect ? UIColor.green.cgColor : UIColor.red.cgColor
цвета не соответсвуют макету

2022-11-23 13:46 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.borderWidth = 8
округления картинок нет

2022-11-23 13:46 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.borderColor = isCorrect ? UIColor.green.cgColor : UIColor.red.cgColor
цвет фона тоже неверный, должен быть YP Black

2022-11-23 13:46 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
Необязательно: если быстро нажимать одну и ту же кнопку, то срабатывают лишние нажатия, пока мы ожидаем следующего вопроса. Чтобы этого не было, можно использовать свойство isEnabled. При начале ожидания "выключать" кнопку, после ожидания "включать" https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled

2022-11-23 13:46 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.borderColor = isCorrect ? UIColor.green.cgColor : UIColor.red.cgColor
цвет рамки не пропадает после переключения на другой вопрос

2022-11-23 13:46 UTC, mmbabaev commented
засабмитил комментарии, извиняюсь

2022-11-23 17:38 UTC, tommypanda10 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.borderColor = isCorrect ? UIColor.green.cgColor : UIColor.red.cgColor
исправил

2022-11-24 08:00 UTC, mmbabaev commented
Все замечания исправлены, но сейчас появилась проблема с цветами и из загрузкой в git. Сейчас если скачать проект с гитхаба, то он крашится, тк цвета загружены с большой буквы, читаются с маленькой. 

Если локально проблемы нет, то возможно проблем с тем, как вы загрузили папки в git https://stackoverflow.com/questions/34702239/git-folder-case-sensitive-issue

2022-11-24 08:01 UTC, mmbabaev commented
Также шрифты не меняются в приложении. В учебнике допущена ошибка, поэтому этот пункт необязателен. 
На скрине показал как нужно сделать: 
1) Шрифты добавлены в Group (серая папка)
2) Шрифтам проставлена галочка Target Membership  (справа)

<img width="1356" alt="Screen Shot 2022-11-17 at 20 15 01" src="https://user-images.githubusercontent.com/12600807/202513128-d74c5681-7a76-4778-ae5b-0fbcd44f0893.png">

Полезная статья, которая помогла мне разобраться в свое время: 
https://codewithchris.com/common-mistakes-with-adding-custom-fonts-to-your-ios-app/

2022-11-25 07:57 UTC, tommypanda10 commented
загрузил цвета все с маленькой буквы + добавил в консоль "git config --global core.ignorecase false", надеюсь помогло

шрифты сделал как на скрине

2022-11-25 09:46 UTC, mmbabaev commented
<img width="347" alt="Screen Shot 2022-11-25 at 12 45 53" src="https://user-images.githubusercontent.com/12600807/203951030-a69570d3-2984-41f8-bd84-96bea6b65d0b.png">
заметил тут еще проблему небольшую: текст должен располагаться по центру, исправьте, пожалуйста

2022-11-25 09:46 UTC, mmbabaev approved these changes

2022-11-27 11:22 UTC, tommypanda10 commented
исправил, спасибо

2022-11-27 11:53 UTC, merged